### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by sargo** [iotcreators/nordic#3]
This repository doesn't seem to have a [license file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#:~:text=You%20can%20include%20an%20open,for%20other%20people%20to%20contribute.). This makes it difficult and unclear for others to freely use, change, or distribute the project.

Would it be possible to add a LICENSE.TXT? Something permissive like MIT License would be great!

**Comment by henrikbrixandersen** [comment]
Or Apache 2.0, which is what Zephyr RTOS itself uses.

**Comment by sargo** [comment]
I see that this repo code was based on the **nRF9160: UDP** sample from nRF SDK (https://github.com/nrfconnect/sdk-nrf/tree/main/samples/nrf9160/udp) which is on **Nordic Semiconductor ASA** license, so it's reasonable to use this one.

**Comment by Marco-Peli** [comment]
licence was added as provided by Nordic Semiconductor
